name: formatted_text_hooks
description: >
  A simple text formatting package.
  Use to format text in TextField and Text widgets. 
  Hooks version of formattd_text.
version: 3.0.0
homepage: https://github.com/NirmalAriyathilake/formatted_text_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  formatted_text: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: null
