name: formatted_text_hooks
description: A simple text formatting package. Hooks version of formattd_text
version: 1.0.0
homepage: https://github.com/NirmalAriyathilake/formatted_text_hooks

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter: null
