name: formatted_text_hooks
description: >
  A simple text formatting package.
  Use to format text in TextField and Text widgets. 
  Hooks version of formatted_text.
version: 3.1.0
homepage: https://github.com/NirmalAriyathilake/formatted_text_hooks

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  formatted_text: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter: null
